### ISSUE TITLE
Issue with port binding

### ISSUE THREAD

**Issue by treeder** [treeder/devo#1]
Copied from: https://github.com/treeder/go/issues/8#issuecomment-152520109

Thanks @treeder. You might want to make some tweaks to https://github.com/treeder/devo

The usage script gives this:

    dj() {
      docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v "$PWD":/app -v $HOME:/root:ro -w /app -p 8080:8080 devo/dj $@
    }

This already occupies port 8080 on the host. Running the sample then yields this error and won't start

     % dj go vendor
    run --rm --name dj_7 -i --volumes-from /distracted_wozniak -p 8080:8080 -w /app iron/go sh -c chmod  a+x __uberscript__ && ./__uberscript__
    Error response from daemon: Cannot start container c3cbdaee414a9eb901dac9930da3e973458b373f18c79f631c5d1afb3059052e: Bind for 0.0.0.0:8080 failed: port is already allocated

I had to change the dj script and give it a less frequently used port on the host to avoid the conflicts. Things worked after that.

**Comment by treeder** [comment]
@berinle you must be running something twice at the same time?  I think it would be best to remove the port binding in the "dj" script and only use it when necessary, ie: when running an app or something. But not sure how to express that. Could be something like:

```
dj go run -p 8080:8080
```

So you explicitly bind on the run command.

**Comment by berinle** [comment]
I verified I wasn't running anything twice via `netstat`, `lsof` and `ps`. It was only the `dj` script as stated above.

That said, I totally agree with your suggestion. Remove the port binding in the `dj` script and allow invokers bind it when running a container. That also feels more natural and doesn't differ from the docker knowledge people already have.

**Comment by treeder** [comment]
Fixed README, removed port.
